# Generated by Django 5.1.15 on 2026-07-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chinese_Ob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rid', models.CharField(max_length=50)),
                ('name', models.TextField()),
                ('tags', models.TextField()),
                ('steps', models.TextField()),
                ('description', models.TextField()),
                ('ingredients', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='recipe_at',
            name='nutrition',
        ),
        migrations.AddField(
            model_name='recipe_at',
            name='calories',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='recipe_at',
            name='carbohydrates',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='recipe_at',
            name='fat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='recipe_at',
            name='protein',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='recipe_at',
            name='saturated_fat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='recipe_at',
            name='sodium',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='recipe_at',
            name='sugar',
            field=models.FloatField(default=0),
        ),
    ]
