# Generated by Django 5.1.15 on 2026-07-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='daily_calories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='輸入時間')),
                ('type', models.IntegerField(choices=[(0, 'None'), (1, 'balence'), (2, 'TooOil'), (3, 'TooMuchRice'), (4, 'lotsVege')], verbose_name='攝取型')),
                ('calories', models.IntegerField(verbose_name='卡路里攝取')),
            ],
        ),
        migrations.CreateModel(
            name='daily_exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='輸入時間')),
                ('strong', models.IntegerField(choices=[(3, 'high'), (2, 'medium'), (1, 'low')], verbose_name='運動強度')),
                ('sport_time', models.IntegerField(verbose_name='運動時間')),
            ],
        ),
        migrations.CreateModel(
            name='daily_water',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='輸入時間')),
                ('water', models.IntegerField(verbose_name='水分攝取')),
            ],
        ),
    ]
