# Generated by Django 5.1.15 on 2026-07-20 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('HealthManage', '0001_initial'),
        ('Member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_calories',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Member.member'),
        ),
        migrations.AddField(
            model_name='daily_exercise',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Member.member'),
        ),
        migrations.AddField(
            model_name='daily_water',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Member.member'),
        ),
    ]
