# Generated by Django 4.1.10 on 2024-02-07 15:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberP',
            fields=[
                ('uid', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='uid')),
                ('account', models.CharField(max_length=50, unique=True, verbose_name='帳號')),
                ('password', models.CharField(max_length=100, verbose_name='密碼')),
                ('is_active', models.BooleanField()),
                ('is_staff', models.BooleanField()),
                ('is_superuser', models.BooleanField()),
                ('last_login', models.DateTimeField(auto_now=True, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('birth', models.DateField(default='2003-06-25')),
                ('email', models.TextField(null=True)),
                ('gender', models.TextField(default='male')),
                ('join_date', models.DateField(default=datetime.date.today)),
                ('會員編號', models.ForeignKey(default='ErrorID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField(default=160)),
                ('weight', models.IntegerField(default=60)),
                ('allergen', models.TextField(null=True)),
                ('prefer', models.TextField(null=True)),
                ('disease', models.TextField(null=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Member.member')),
            ],
        ),
    ]
