# Generated by Django 5.0.2 on 2024-03-19 18:40

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberP',
            fields=[
                ('uid', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='uid')),
                ('account', models.CharField(max_length=50, unique=True, verbose_name='帳號')),
                ('password', models.CharField(max_length=100, verbose_name='密碼')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(auto_now=True, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Prefer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.TextField(verbose_name='飲食目標')),
                ('restrict', models.TextField(verbose_name='飲食限制')),
                ('prefer', models.IntegerField(choices=[(1, 'lose weight'), (3, 'build muscle'), (2, 'keep health'), (4, 'control blood sugar'), (5, 'control cholesterol')], verbose_name='飲食偏好')),
                ('Nut_need', models.TextField(verbose_name='營養需求')),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('birth', models.DateField(default='2003-06-25')),
                ('email', models.TextField()),
                ('gender', models.TextField(default='male')),
                ('job', models.TextField(default='None')),
                ('join_date', models.DateField(default=datetime.date.today)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('uid', models.ForeignKey(default='ErrorID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField(default=160, verbose_name='身高')),
                ('weight', models.FloatField(default=60, verbose_name='體重')),
                ('mental', models.TextField(null=True, verbose_name='心理因素')),
                ('exercise_intensity', models.IntegerField(choices=[(4, 'high'), (3, 'medium'), (2, 'low'), (1, 'None')], default=1, null=True, verbose_name='運動強度')),
                ('excercise_frequency', models.IntegerField(choices=[(5, 'Everyday'), (4, '5 times or more'), (3, '3-4 times'), (2, '1-2 times'), (1, 'never')], default=1, null=True, verbose_name='運動頻率（週）')),
                ('excercise_time', models.IntegerField(choices=[(3, 'LongTime'), (2, 'ShortTime'), (1, 'None')], default=1, null=True, verbose_name='運動時間')),
                ('allergen', models.TextField(null=True, verbose_name='過敏原')),
                ('disease', models.TextField(null=True, verbose_name='慢性病')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
# Generated by Django 5.0.2 on 2024-03-19 18:40

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberP',
            fields=[
                ('uid', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='uid')),
                ('account', models.CharField(max_length=50, unique=True, verbose_name='帳號')),
                ('password', models.CharField(max_length=100, verbose_name='密碼')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(auto_now=True, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Prefer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.TextField(verbose_name='飲食目標')),
                ('restrict', models.TextField(verbose_name='飲食限制')),
                ('prefer', models.IntegerField(choices=[(1, 'lose weight'), (3, 'build muscle'), (2, 'keep health'), (4, 'control blood sugar'), (5, 'control cholesterol')], verbose_name='飲食偏好')),
                ('Nut_need', models.TextField(verbose_name='營養需求')),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('birth', models.DateField(default='2003-06-25')),
                ('email', models.TextField()),
                ('gender', models.TextField(default='male')),
                ('job', models.TextField(default='None')),
                ('join_date', models.DateField(default=datetime.date.today)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('uid', models.ForeignKey(default='ErrorID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField(default=160, verbose_name='身高')),
                ('weight', models.FloatField(default=60, verbose_name='體重')),
                ('mental', models.TextField(null=True, verbose_name='心理因素')),
                ('exercise_intensity', models.IntegerField(choices=[(4, 'high'), (3, 'medium'), (2, 'low'), (1, 'None')], default=1, null=True, verbose_name='運動強度')),
                ('excercise_frequency', models.IntegerField(choices=[(5, 'Everyday'), (4, '5 times or more'), (3, '3-4 times'), (2, '1-2 times'), (1, 'never')], default=1, null=True, verbose_name='運動頻率（週）')),
                ('excercise_time', models.IntegerField(choices=[(3, 'LongTime'), (2, 'ShortTime'), (1, 'None')], default=1, null=True, verbose_name='運動時間')),
                ('allergen', models.TextField(null=True, verbose_name='過敏原')),
                ('disease', models.TextField(null=True, verbose_name='慢性病')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
