# Generated by Django 5.0.2 on 2024-02-15 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='會員編號',
            new_name='uid',
        ),
    ]
