# Generated by Django 5.0.2 on 2024-02-15 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0002_rename_會員編號_member_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberp',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='memberp',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='memberp',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
