# Generated by Django 5.0.2 on 2024-02-15 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0003_alter_memberp_is_active_alter_memberp_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='health',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
