# Generated by Django 5.0.2 on 2024-02-16 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0004_alter_health_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='health',
            name='update_time',
        ),
        migrations.AddField(
            model_name='health',
            name='excercise_frequency',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='health',
            name='exercise_intensity',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='health',
            name='mental',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='job',
            field=models.TextField(default='None'),
        ),
        migrations.AddField(
            model_name='member',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='Prefer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.TextField()),
                ('water_gain', models.TextField(choices=[(1, 'less than one liter'), (2, '1-2 liter'), (3, '2-3 liter'), (4, '3 liters or more'), (5, 'uncertain')], null=True)),
                ('eating_time', models.TextField(null=True)),
                ('eating_habit', models.TextField(null=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
