# Generated by Django 5.0.2 on 2024-02-16 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0005_remove_health_update_time_health_excercise_frequency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='health',
            name='excercise_time',
            field=models.IntegerField(choices=[(3, 'LongTime'), (2, 'ShortTime'), (1, 'None')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='health',
            name='excercise_frequency',
            field=models.IntegerField(choices=[(5, 'Everyday'), (4, '5 times or more'), (3, '3-4 times'), (2, '1-2 times'), (1, 'never')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='health',
            name='exercise_intensity',
            field=models.IntegerField(choices=[(4, 'high'), (3, 'medium'), (2, 'low'), (1, 'None')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='health',
            name='height',
            field=models.FloatField(default=160),
        ),
        migrations.AlterField(
            model_name='health',
            name='weight',
            field=models.FloatField(default=60),
        ),
        migrations.AlterField(
            model_name='prefer',
            name='water_gain',
            field=models.IntegerField(choices=[(1, 'uncertain'), (2, 'less than one liter'), (3, '1-2 liter'), (4, '2-3 liter'), (5, '3 liters or more')], default=1, null=True),
        ),
    ]
