# Generated by Django 5.0.1 on 2024-02-26 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='問題類別名稱')),
            ],
        ),
        migrations.CreateModel(
            name='Record_DataChange',
            fields=[
                ('index', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('ip_address', models.TextField()),
                ('change_date', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.TextField()),
                ('change_type', models.CharField(max_length=50)),
                ('change_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Record_Output',
            fields=[
                ('index', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('recordId', models.TextField()),
                ('recipeId', models.TextField()),
                ('output_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Record_Search',
            fields=[
                ('index', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('ip_address', models.TextField()),
                ('recordId', models.TextField()),
                ('searchText', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('qid', models.IntegerField(primary_key=True, serialize=False, verbose_name='題目編號')),
                ('content', models.TextField(verbose_name='題目')),
                ('option', models.TextField(verbose_name='選項')),
                ('difficulty', models.IntegerField(verbose_name='難度')),
                ('right_answer', models.IntegerField(choices=[('A', 1), ('B', 2), ('C', 3), ('D', 4)], verbose_name='正確答案')),
                ('cate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Record.category')),
            ],
        ),
        migrations.CreateModel(
            name='Record_Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_id', models.IntegerField()),
                ('answer', models.IntegerField(choices=[('A', 1), ('B', 2), ('C', 3), ('D', 4)])),
                ('is_post_test', models.BooleanField(default=False, verbose_name='是否為後側')),
                ('qid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Record.question')),
            ],
        ),
    ]
