# Generated by Django 4.1.10 on 2024-02-07 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record_DataChange',
            fields=[
                ('index', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('ip_address', models.TextField()),
                ('change_date', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.TextField()),
                ('change_type', models.CharField(max_length=50)),
                ('change_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Record_Output',
            fields=[
                ('index', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('recordId', models.TextField()),
                ('recipeId', models.TextField()),
                ('output_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Record_Search',
            fields=[
                ('index', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('ip_address', models.TextField()),
                ('recordId', models.TextField()),
                ('searchText', models.TextField()),
            ],
        ),
    ]
