# Generated by Django 5.0.2 on 2024-04-10 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='問題類別名稱')),
            ],
        ),
        migrations.CreateModel(
            name='Record_DataChange',
            fields=[
                ('index', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('ip_address', models.TextField()),
                ('change_date', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.TextField()),
                ('change_type', models.CharField(max_length=50)),
                ('change_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Record_Output',
            fields=[
                ('index', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('recordId', models.TextField()),
                ('recipeId', models.TextField()),
                ('output_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Record_Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_id', models.IntegerField(verbose_name='作答者ID')),
                ('score', models.IntegerField(verbose_name='分數')),
                ('is_post_test', models.BooleanField(verbose_name='是否為後側')),
            ],
        ),
        migrations.CreateModel(
            name='Record_Search',
            fields=[
                ('index', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('ip_address', models.TextField()),
                ('recordId', models.TextField()),
                ('searchText', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('qid', models.IntegerField(primary_key=True, serialize=False, verbose_name='題目編號')),
                ('content', models.TextField(verbose_name='題目')),
                ('option1', models.TextField(null=True, verbose_name='選項1')),
                ('option2', models.TextField(null=True, verbose_name='選項2')),
                ('option3', models.TextField(null=True, verbose_name='選項3')),
                ('option4', models.TextField(null=True, verbose_name='選項4')),
                ('difficulty', models.IntegerField(choices=[(1, 'easy'), (2, 'normal'), (3, 'hard')], verbose_name='難度')),
                ('right_answer', models.IntegerField(choices=[(1, 'A'), (2, 'B'), (3, 'C'), (4, 'D')], verbose_name='正確答案')),
                ('cate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Record.category')),
            ],
        ),
        migrations.CreateModel(
            name='Record_CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('qid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Record.question')),
            ],
        ),
        migrations.CreateModel(
            name='Record_Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.IntegerField(choices=[(1, 'A'), (2, 'B'), (3, 'C'), (4, 'D')])),
                ('is_post_test', models.BooleanField(default=False, verbose_name='是否為後側')),
                ('qid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Record.question')),
                ('answer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Record.record_score')),
            ],
        ),
    ]
