# Generated by Django 5.0.1 on 2024-02-26 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Record', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='option',
        ),
        migrations.AddField(
            model_name='question',
            name='option1',
            field=models.TextField(null=True, verbose_name='選項1'),
        ),
        migrations.AddField(
            model_name='question',
            name='option2',
            field=models.TextField(null=True, verbose_name='選項2'),
        ),
        migrations.AddField(
            model_name='question',
            name='option3',
            field=models.TextField(null=True, verbose_name='選項3'),
        ),
        migrations.AddField(
            model_name='question',
            name='option4',
            field=models.TextField(null=True, verbose_name='選項4'),
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.IntegerField(choices=[('easy', 1), ('normal', 2), ('hard', 3)], verbose_name='難度'),
        ),
    ]
