# Generated by Django 5.1.15 on 2026-07-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Record', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record_search',
            name='searchEngText',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='record_search',
            name='ip_address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='record_search',
            name='recordId',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='record_search',
            name='searchText',
            field=models.TextField(null=True),
        ),
    ]
